spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:server}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
    hikari:
      data-source-properties:
        stringtype: unspecified
  docker:
    compose:
      file: "./server/compose.yml"
      enabled: false
      lifecycle-management: start_and_stop
  threads:
    virtual:
      enabled: true

springdoc:
  writer-with-order-by-keys: true
  api-docs:
    path: /v3/api-docs/openapi.json
