name: run-tests

on: workflow_call

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-build-${{ github.head_ref || github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-build-master
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle
            ./**/build
            ./**/node_modules

      - name: Run assemble
        run: ./gradlew assemble

      - name: Run check
        run: ./gradlew check
